// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("CSharpExampleLib")]
[assembly: AssemblyProductAttribute("InteropPresentation")]
[assembly: AssemblyDescriptionAttribute("Code to accompany interop talk")]
[assembly: AssemblyVersionAttribute("1.0")]
[assembly: AssemblyFileVersionAttribute("1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0";
        internal const string InformationalVersion = "1.0";
    }
}
